### ISSUE TITLE
Unable to npm install latest build?

### ISSUE THREAD

**Issue by JoshElias** [gdi2290/angular-starter#1930]
I'm getting the following error when trying to install the latest build. 

```
C:\Users\Josh\Projects>git clone --depth 1 https://github.com/AngularClass/angular-starter.git
Cloning into 'angular-starter'...
remote: Counting objects: 154, done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 154 (delta 12), reused 108 (delta 5), pack-reused 0
Receiving objects: 100% (154/154), 299.66 KiB | 633.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.

C:\Users\Josh\Projects>cd angular-starter

C:\Users\Josh\Projects\angular-starter>npm install -g node-pre-gyp
C:\Users\Josh\AppData\Roaming\npm\node-pre-gyp -> C:\Users\Josh\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp
+ node-pre-gyp@0.6.39
updated 1 package in 3.348s

C:\Users\Josh\Projects\angular-starter>npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> node-sass@4.7.2 install C:\Users\Josh\Projects\angular-starter\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Josh\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> coffee-script@1.12.8 postinstall C:\Users\Josh\Projects\angular-starter\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
npm WARN @angular/compiler-cli@5.0.3 requires a peer of typescript@>=2.4.2 <2.5 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.1.1 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.1.1 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.24.1 requires a peer of typescript@2.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN ts-simple-ast@0.86.0 requires a peer of typescript@2.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Josh\AppData\Roaming\npm-cache\_logs\2017-11-30T14_22_10_132Z-debug.log
```

**Comment by JoshElias** [comment]
Seems to be a deprecated CoffeeScript dependency?
