### ISSUE TITLE
Unable to run npm build without errors if add ng-socket-io package to project!

### ISSUE THREAD

**Issue by JoelParke** [gdi2290/angular-starter#1931]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a Bug report**

If I add a socket.service.ts using the package ng-socket-io to the project by adding the socket.service.ts service to the project and add a bit of code into app.module.ts 

        import { Socket, SocketIoModule, SocketIoConfig } from 'ng-socket-io';
        import { SocketService } from './socket.service';
        // SocketIoConfig
        const config:
          SocketIoConfig  = { url: 'https://localhost', options: {} };

and add the SocketService provider:

       providers: [
          environment.ENV_PROVIDERS,
          APP_PROVIDERS,
          {
            provide: SocketService,
            useFactory: (socket: Socket) => {
              return new SocketService(socket);
            },
            deps: [Socket]
          },
        ]

and the file socket.service.ts  to the project:

      import { Injectable } from '@angular/core';
      import { Socket } from 'ng-socket-io';
      
      @Injectable()
      export class SocketService {
        public id: string;
      
        constructor(private socket: Socket) {
          socket.on('connect', (ev: any) => {
            this.id = socket.ioSocket.id;
          });
          socket.on('disconnect', (ev: any) => {
            this.id = null;
          });
          socket.on('disconnecting', (ev: any) => {
            console.log('disconnecting ID:', socket.ioSocket.id);
          });
        }
      
        public close() {
          console.log('closing');
          this.socket.disconnect();
        }
      }

the project fails to build!!

* **What is the current behavior?**
Run 'npm run build' and see:

            > angular-starter@7.0.0 build /home/joel/workspace/angular-starter
            > npm run build:dev
            .
            .
            .
            > angular-starter@7.0.0 webpack /home/joel/workspace/angular-starter
            > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.dev.js" "--progress" "--profile"
            
            2076ms building modules                                                                 
            6ms sealing 
            0ms optimizing 
            1ms basic module optimization 
            8ms module optimization 
            4ms advanced module optimization 
            3ms basic chunk optimization        
            0ms chunk optimization 
            0ms advanced chunk optimization 
            1ms module and chunk tree optimization 
            0ms chunk modules optimization 
            0ms advanced chunk modules optimization 
            1ms module reviving 
            3ms module order optimization 
            2ms module id optimization 
            1ms chunk reviving 
            0ms chunk order optimization 
            4ms chunk id optimization 
            26ms hashing
            0ms module assets processing 
            1674ms chunk assets processing
            1ms additional chunk assets processing 
            0ms recording 
            0ms additional asset processing 
            0ms chunk asset optimization 
            77ms asset optimization
            149ms emitting
            Hash: bf86ad86435f34290435
            Version: webpack 3.8.1
            Time: 6405ms
                                             Asset       Size  Chunks                    Chunk Names
                  assets/icon/apple-icon-60x60.png    3.56 kB          [emitted]         
                                        0.chunk.js    9.35 kB       0  [emitted]         
                                        2.chunk.js    9.35 kB       2  [emitted]         
                                        3.chunk.js    9.33 kB       3  [emitted]         
                                        4.chunk.js  876 bytes       4  [emitted]         
                                    main.bundle.js    9.16 MB       5  [emitted]  [big]  main
                               polyfills.bundle.js     595 kB       6  [emitted]  [big]  polyfills
                                  inline.bundle.js     5.8 kB       7  [emitted]         inline
                               assets/css/.gitkeep   14 bytes          [emitted]         
                                  assets/data.json   30 bytes          [emitted]         
                                 assets/humans.txt  251 bytes          [emitted]         
              assets/icon/android-icon-192x192.png    9.71 kB          [emitted]         
              assets/icon/android-icon-144x144.png    8.43 kB          [emitted]         
                assets/icon/android-icon-48x48.png    2.92 kB          [emitted]         
                assets/icon/android-icon-72x72.png    4.23 kB          [emitted]         
                assets/icon/android-icon-36x36.png     2.3 kB          [emitted]         
                assets/icon/android-icon-96x96.png     5.6 kB          [emitted]         
                assets/icon/apple-icon-114x114.png    6.55 kB          [emitted]         
                assets/icon/apple-icon-120x120.png    6.92 kB          [emitted]         
                assets/icon/apple-icon-144x144.png    8.43 kB          [emitted]         
                assets/icon/apple-icon-152x152.png    8.99 kB          [emitted]         
                assets/icon/apple-icon-180x180.png      11 kB          [emitted]         
                  assets/icon/apple-icon-57x57.png     3.4 kB          [emitted]         
                                        1.chunk.js    9.33 kB       1  [emitted]         
                  assets/icon/apple-icon-72x72.png    4.23 kB          [emitted]         
            assets/icon/apple-icon-precomposed.png    10.3 kB          [emitted]         
                  assets/icon/apple-icon-76x76.png    4.46 kB          [emitted]         
                        assets/icon/apple-icon.png    10.3 kB          [emitted]         
                     assets/icon/browserconfig.xml  281 bytes          [emitted]         
                     assets/icon/favicon-16x16.png    1.52 kB          [emitted]         
                     assets/icon/favicon-32x32.png    2.07 kB          [emitted]         
                     assets/icon/favicon-96x96.png     5.6 kB          [emitted]         
                           assets/icon/favicon.ico    1.15 kB          [emitted]         
                   assets/icon/ms-icon-144x144.png    8.43 kB          [emitted]         
                   assets/icon/ms-icon-150x150.png    8.88 kB          [emitted]         
                   assets/icon/ms-icon-310x310.png    24.1 kB          [emitted]         
                     assets/icon/ms-icon-70x70.png    4.12 kB          [emitted]         
                            assets/img/angular.png      19 kB          [emitted]         
                              assets/manifest.json  654 bytes          [emitted]         
                   assets/mock-data/mock-data.json   22 bytes          [emitted]         
                               assets/img/tipe.png    45.9 kB          [emitted]         
                                 assets/robots.txt   31 bytes          [emitted]         
                          assets/service-worker.js   44 bytes          [emitted]         
                                        humans.txt  251 bytes          [emitted]         
                                        robots.txt   31 bytes          [emitted]         
                                        index.html    2.71 kB          [emitted]         
            [./$$_lazy_route_resource lazy recursive] ./$$_lazy_route_resource lazy 160 bytes {5} [built]
                   [] -> factory:9ms building:0ms = 9ms
            [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {5} {6} [built]
                   [] -> factory:0ms building:1ms = 1ms
            [./src/app/app.module.ts] ./src/app/app.module.ts 2.78 kB {5} [built]
                   [] -> factory:224ms building:4ms dependencies:674ms = 902ms
            [./src/app/app.resolver.ts] ./src/app/app.resolver.ts 572 bytes {5} [built]
                   [] -> factory:23ms building:1ms dependencies:649ms = 673ms
            [./src/app/app.routes.ts] ./src/app/app.routes.ts 479 bytes {5} [built]
                   [] -> factory:18ms building:1ms dependencies:97ms = 116ms
            [./src/app/app.service.ts] ./src/app/app.service.ts 1.32 kB {5} [built]
                   [] -> factory:28ms building:1ms dependencies:645ms = 674ms
            [./src/app/home/index.ts] ./src/app/home/index.ts 34 bytes {5} [built]
                   [] -> factory:114ms building:0ms = 114ms
            [./src/app/home/x-large/index.ts] ./src/app/home/x-large/index.ts 37 bytes {5} [built]
                   [] -> factory:116ms building:1ms = 117ms
            [./src/app/index.ts] ./src/app/index.ts 45 bytes {5} [built]
                   [] -> factory:198ms building:1ms = 199ms
            [./src/app/no-content/index.ts] ./src/app/no-content/index.ts 40 bytes {5} [built]
                   [] -> factory:116ms building:0ms = 116ms
            [./src/app/socket.service.ts] ./src/app/socket.service.ts 908 bytes {5} [built]
                   [] -> factory:13ms building:1ms dependencies:677ms = 691ms
            [./src/environments/environment.ts] ./src/environments/environment.ts 830 bytes {5} [built]
                   [] -> factory:190ms building:1ms = 191ms
            [./src/main.browser.ts] ./src/main.browser.ts 966 bytes {5} [built]
                    factory:2355ms building:8ms = 2363ms
            [./src/polyfills.browser.ts] ./src/polyfills.browser.ts 2.65 kB {6} [built]
                    factory:2355ms building:5ms = 2360ms
            [./src/styles/styles.scss] ./src/styles/styles.scss 1.16 kB {5} [built]
                   [] -> factory:358ms building:11ms = 369ms
                + 231 hidden modules
     
            ERROR in ./node_modules/ng-socket-io/socket-io.module.ts
            Module build failed: Error: /home/joel/workspace/angular-starter/node_modules/ng-socket-io/socket-io.module.ts is not part of the compilation output. Please check the other error messages for details.
                at AngularCompilerPlugin.getCompiledFile (/home/joel/workspace/angular-starter/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
                at plugin.done.then (/home/joel/workspace/angular-starter/node_modules/@ngtools/webpack/src/loader.js:467:39)
                at <anonymous>
                at process._tickCallback (internal/process/next_tick.js:188:7)
             @ ./node_modules/ng-socket-io/index.js 3:25-54
             @ ./src/app/app.module.ts
             @ ./src/app/index.ts
             @ ./src/main.browser.ts

            ERROR in ./node_modules/ng-socket-io/socket-io.service.ts
            Module build failed: Error: /home/joel/workspace/angular-starter/node_modules/ng-socket-io/socket-io.service.ts is not part of the compilation output. Please check the other error messages for details.
                at AngularCompilerPlugin.getCompiledFile (/home/joel/workspace/angular-starter/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
                at plugin.done.then (/home/joel/workspace/angular-starter/node_modules/@ngtools/webpack/src/loader.js:467:39)
                at <anonymous>
                at process._tickCallback (internal/process/next_tick.js:188:7)**
             @ ./node_modules/ng-socket-io/index.js 5:26-56
             @ ./src/app/app.module.ts
             @ ./src/app/index.ts
             @ ./src/main.browser.ts
            Child html-webpack-plugin for "index.html":
                 1 asset
                [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 2.1 kB {0} [built]
                        factory:2341ms building:14ms = 2355ms
                [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
                       [] -> factory:12ms building:4ms = 16ms
                [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
                       [] -> factory:12ms building:4ms = 16ms
                    + 1 hidden module

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
See the angularStarter.zip file below -- as an easier way to reproduce.

* **What is the expected behavior?**
For the project to still build, serve, etc...

* **What is the motivation / use case for changing the behavior?**
Perhaps there is an issue with libraries of the type ng-socket-io and angular5, but I am stuck dead in the water in moving from v1.5.0 to the current build which supports Angular5.  

* **Please tell us about your environment:**
Ubuntu, Intellij, Angular5 - v5.0.5 
(I simply did a ncu -u on the 'angular-starter' to bring all packages up to date).

- Browser: n.a.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Here is the added file (socket.service.ts), the edited app.module.ts, and zipped up the resultant angular-starter (after npm run clean) (in a zip file):
[angularStarter.zip](https://github.com/gdi2290/angular-starter/files/1525097/angularStarter.zip)
So to reproduce, simply do:
yarn
npm run build

**Comment by JoelParke** [comment]
I worked around this issue -- which I believe is ONLY a webpack issue and and not an issue with this project.  I moved pieces of the ng-socket-io internals into a component which was using ng-socket-io and then it builds fine.
