### ISSUE TITLE
CI Build failing

### ISSUE THREAD

**Issue by tsukhu** [gdi2290/angular-starter#1954]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
The travis CI build is broken .. 

I was working on the PR #1881 and its failing due to an unconnected issue with respect to a travis build . It is failing while running the protractor tests
> angular-starter@7.0.0 protractor /home/travis/build/gdi2290/angular-starter
> protractor
[06:27:41] I/launcher - Running 1 instances of WebDriver
[06:27:41] I/direct - Using ChromeDriver directly...
[06:28:41] E/runner - Unable to start a WebDriver session.
[06:28:41] E/launcher - Error: WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.14.12-041412-generic x86_64)
    at WebDriverError (/home/travis/build/gdi2290/angular-starter/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/home/travis/build/gdi2290/angular-starter/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/travis/build/gdi2290/angular-starter/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/travis/build/gdi2290/angular-starter/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[06:28:41] E/launcher - Process exited with error code 100

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

No failures

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by lanovoy** [comment]
Got it fixed. It's recommended to use --no-sandbox together with --headless for CI builds (if Chrome is used).
